### ISSUE TITLE
Update react native version & dependencies

### ISSUE THREAD

**Issue by ignaciosantise** [Psychedelic/plug-mobile#469]
## Description
* Update react native to 0.69.6
* Update dependencies

## Comments for QA
* A full test of the application is needed
* Regression test coming from production app (0.2.1)

**Comment by alinasytnik** [comment]
#Issue

## Description
App crashes when the user tries to add the new contact with ICNS.

## Steps to Reproduce
1. Unlock wallet.
2. Go to Settings.
3. Click on Contacts.
4. Click on Add contact button.
5. Fill name field.
6. Fill "PID, AID, ICNS" field with existing ICNS 
**Current:** Notice that the app crashes. 


## Expected behavior
The app shouldn't crash, and contact with ICNS should be added to the contact book.

## Screenshots
https://user-images.githubusercontent.com/33018206/194143928-9f894715-acef-4c82-aa9a-97caf77a59f5.mp4


## Smartphone (please complete the following information):
 - Device: iPhone 14
 - OS: iOS 16.0.1
 - Version 0.3.0(3)

**Comment by alinasytnik** [comment]
## **⚠️Issue**

## Description
App crashes when the user tries to send tokens to the account using ICNS name.

## Steps to Reproduce
1. Unlock wallet.
2. Go to token tab.
3. Click on ICP.
4. Click on Send button.
5. Fill "To:" field with ICNS name.
**Current:** Notice that the app crashes.


## Expected behavior
The app shouldn't crash, and sending ICP using ICNS should be successful.

## Screenshots

https://user-images.githubusercontent.com/33018206/194145753-3275f8e0-4a67-4484-a6c9-ee2e41fa7292.MP4



## Smartphone (please complete the following information):
 - Device: iPhone 14
 - OS: iOS 16.0.1
 - Version 0.3.0(3)

**Comment by alinasytnik** [comment]
## **⚠️Issue**

## Description
An error occurs after Wallet Deleting. 

## Steps to Reproduce
1. Unlock wallet.
2. Go to Settings.
3. Click on the Delete Wallet button.
4. Confirm the deleting.
**Current:** Notice that an error was shown. 

## Expected behavior
After wallet deletion user should be taken to the Import/Create Wallet flow.

## Screenshots
https://user-images.githubusercontent.com/33018206/194147042-10278565-d193-4a21-9890-39fc7b42a925.mp4

## Smartphone (please complete the following information):
 - Device: iPhone 14
 - OS: iOS 16.0.1
 - Version 0.3.0(3)

**Comment by kevin4476** [comment]
Problems found in iOS are not present in Android

**Comment by kevin4476** [comment]
App doesn't allow type correctly
--
## Testing Information

- **OS:** Android
- **Cellphone** **version:** Samsung Galaxy Note 9
- **Software version:** 8.1.0
- **Samsung Experience:** 9.5
- **Version Plug mobile:** 0.3.0(21)

## Precondition

- Have the Samsung Galaxy Note 9 with the software version 8.1.0

---

**Issue:** When I try to write in the application it starts to repeat the letters already written 

- **Steps to recreate**
    - Launch app
    - Press any token
    - Press Send button
    - Try to write anything
- **Current:** The app will repeat what you type
    
   

https://user-images.githubusercontent.com/108067829/194193479-dc15fad9-82e5-4409-9d06-bee79a072091.mp4


    
- **Expected:** The app should allow write anything without problems

### Additional Notes

**This mistake is present in the followings screens:**

1. Typing the name of a contact
2. When adding a contact
3. Typing the recovery phrase **(It only appears here if you disable the hide the password)**
4. Typing a contact's name in the send asset flow

**Comment by kevin4476** [comment]
[⚠️Bug] App doesn’t allow to open edit account menu
--
## Testing Information

- **OS:** Android ****
- **Cellphone** **version:** Samsung Galaxy Note 9
- **Version Plug mobile:** 0.3.0(21)

## Precondition

- Have the last version of plug mobile

---

**Issue: The app doesn’t allow me edit the account**

- **Steps to recreate**
    - Launch app
    - Go to Profile tab
    - Press Change button
    - Press the button with the three point
- **Current:** When pressing the button the application doesn’t open the menu

https://user-images.githubusercontent.com/108067829/194195573-f6d22300-0b72-4ef5-b4e4-82334cc5e63f.mp4


- **Expected:** The app must open the edit account menu

**Comment by alinasytnik** [comment]
## **⚠️Bug**

## Description
The app allows adding the contact with the same name if the user does that from the Send tokens flow. 

## Steps to Reproduce
1. Unlock wallet.
2. Go to the Tokens tab.
3. Click on a random token to send it.
4. Fill the To input with PID, which is not added to the Contacts.
5. Click the Plus icon button to add this PID to Contacts.
6. Fill the name field with a name that has already been added to the Contacts.
**Current:** Notice that the "Name is already taken!" error doesn’t appear, and this contact was added to the Contacts. 


## Expected behavior
"Name is already taken!" error should appear and this contact shouldn't be added to the Contacts.

## Screenshots

https://user-images.githubusercontent.com/33018206/195421416-a42e33c9-805e-45ea-8cfc-9a846075e858.MP4



## Smartphone (please complete the following information):
 - Device: iPhone 14
 - OS: iOS 16.0.1
 - Version 0.3.0(6)
