### ISSUE TITLE
Adapt Front to NFTs virtualization

### ISSUE THREAD

**Issue by ignaciosantise** [Psychedelic/plug-mobile#485]
## Description
- Update way of handling NFTs.

## Comments for QA
- Test NFT tab, NFT detail view and the view of NFTs in the Send, also the reviewSend modal with an NFT selected. (no need to send an NFT to test this)

**Comment by alinasytnik** [comment]
## **⚠️Bug**

## Description
NFT Sending is not processed.

## Steps to Reproduce
1. Login into Plug
2. Go to the Collectibles tab
3. Choose the NFT to send
4. Try to send NFT
**Current:** Notice that NFT doesn’t send successfully.

## Expected behavior
The NFT sending should be processed successfully. 

## Screenshots

![IMG_2968](https://user-images.githubusercontent.com/33018206/199827386-a2816b73-01dc-4242-aae7-bfa5326585b6.PNG)


## Smartphone:
 - Device: iPhone 14
 - OS: iOS 16.0.1
 - Version 0.3.0(10)
