### ISSUE TITLE
Export DFX identities

### ISSUE THREAD

**Issue by riveign** [Psychedelic/plug-mobile#499]
# Description

We want to add the possibility to the user to export their DFX identities via pem files. The user should be able to download all the identities from the different IC accounts they have, but in the future there might be identities that are now downloadable so we need to take it into consideration.

Designs: https://www.figma.com/file/no61f8MMPQlPUIaXSX3zCn/Plug---Wallet?node-id=10697%3A13836

**Comment by alinasytnik** [comment]
## **✳️Improvement**

## Description
The Continue button on the Unlock Export DFX Identity screen modal isn't disabled when the Password input is empty or filled with less than 8 characters.  

## Steps to Reproduce
1. Open the Plug app
2. Create a wallet
3. Go to the Activity tab
4. Click the Settings button
6. Click the Export DFX Identity 
7. Click on the "I'll be safe with my DFX Identity" checkbox 
**Current:** Notice that the Continue button became able, although the Password input is empty (or < 8 chars)

## Expected behavior
The Continue button must be disabled until the Password input is filled with more than 8 characters.

## Screenshots
![IMG_2242](https://user-images.githubusercontent.com/33018206/197545343-2aadac25-69bb-4e5a-840f-580d08f087a4.PNG)



## Smartphone (please complete the following information):
 - Device: iPhone 14 Pro
 - OS: iOS 16.0.1
 - Version 0.3.0(9)
